# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\psoc\theory\pwm_motor_servo\pwm.cydsn\pwm.cyprj
# Date: Mon, 05 Sep 2022 02:59:44 GMT
#set_units -time ns
create_clock -name {clock(FFB)} -period 20000 -waveform {0 10000} [list [get_pins {ClockBlock/ff_div_10}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {clock} -source [get_pins {ClockBlock/hfclk}] -edges {1 481 961} [list]


# Component constraints for D:\psoc\theory\pwm_motor_servo\pwm.cydsn\TopDesign\TopDesign.cysch
# Project: D:\psoc\theory\pwm_motor_servo\pwm.cydsn\pwm.cyprj
# Date: Mon, 05 Sep 2022 02:59:41 GMT
