/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Led_1.h"
#include "Led_1_aliases.h"
#include "Led_2.h"
#include "Led_2_aliases.h"
#include "Led_3.h"
#include "Led_3_aliases.h"
#include "Led_4.h"
#include "Led_4_aliases.h"
#include "Led_5.h"
#include "Led_5_aliases.h"
#include "Led_6.h"
#include "Led_6_aliases.h"
#include "Led_7.h"
#include "Led_7_aliases.h"
#include "Control_Led7_1.h"
#include "Control_Led7_1_aliases.h"
#include "Control_Led7_2.h"
#include "Control_Led7_2_aliases.h"
#include "Control_Led7_3.h"
#include "Control_Led7_3_aliases.h"
#include "Control_Led7_4.h"
#include "Control_Led7_4_aliases.h"
#include "Led_8.h"
#include "Led_8_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

