/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "i2c.h"
#include "i2c_I2C.h"
#include "i2c_PINS.h"
#include "i2c_I2C_PVT.h"
#include "i2c_PVT.h"
#include "i2c_BOOT.h"
#include "LedYellow_0.h"
#include "LedYellow_0_aliases.h"
#include "LedYellow_1.h"
#include "LedYellow_1_aliases.h"
#include "button.h"
#include "button_aliases.h"
#include "LedYellow_2.h"
#include "LedYellow_2_aliases.h"
#include "LedYellow_3.h"
#include "LedYellow_3_aliases.h"
#include "LedYellow_4.h"
#include "LedYellow_4_aliases.h"
#include "LedYellow_5.h"
#include "LedYellow_5_aliases.h"
#include "LedYellow_6.h"
#include "LedYellow_6_aliases.h"
#include "LedYellow_7.h"
#include "LedYellow_7_aliases.h"
#include "timer.h"
#include "timer_interrupt.h"
#include "Clock_1.h"
#include "i2c_SCBCLK.h"
#include "i2c_sda.h"
#include "i2c_sda_aliases.h"
#include "i2c_scl.h"
#include "i2c_scl_aliases.h"
#include "i2c_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

